### ISSUE TITLE
Sell method

### ISSUE THREAD

**Issue by mrubino22** [fdundjer/solana-sniper-bot#22] opened 2024-01-31 20:42 UTC
@fdundjer  Is it possible to have a method for selling sol tokens? possibly with a timed strategy?

**Comment by UmbrellaDot** [comment] 2024-02-02 18:13
![{52622575-FFEE-4d85-9B29-E2EBD497E381}](https://github.com/fdundjer/solana-sniper-bot/assets/53512011/7fb65a46-4cf1-438f-800f-f5da98024243)
购买之后获取代币余额。
![{E3A8E17F-6449-4a6f-B82C-51FADCAE6B52}](https://github.com/fdundjer/solana-sniper-bot/assets/53512011/19f80fdd-7755-4c61-b24b-6602c2e687c7)
卖出代币只需要交互In和out。
![{EC0777FC-5321-43bf-B033-D5880912A25F}](https://github.com/fdundjer/solana-sniper-bot/assets/53512011/6a2dda6f-6f09-4439-99a4-9c7ad02ff5f8)
获取池子sol余额，如果大于10个sol才购买。

**Comment by mrubino22** [comment] 2024-02-02 19:02
> ![{52622575-FFEE-4d85-9B29-E2EBD497E381}](https://private-user-images.githubusercontent.com/53512011/301932089-7fb65a46-4cf1-438f-800f-f5da98024243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDA3MzgsIm5iZiI6MTcwNjkwMDQzOCwicGF0aCI6Ii81MzUxMjAxMS8zMDE5MzIwODktN2ZiNjVhNDYtNGNmMS00MzhmLTgwMGYtZjVkYTk4MDI0MjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE5MDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZGU3MTFiNjI1Njk4ZjU0ZDVlNDkxNTdlNmY2ZThlZjRkNDkxM2VjNzgwYjY5ZjYyNzdhYmU2MDI4NDQzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q0FuwzYSXFPqDcGfZHTVYdGemSaSHO9wrloRg1Zbqf0)
> 购买之后获取代币余额。
> ![{E3A8E17F-6449-4a6f-B82C-51FADCAE6B52}](https://private-user-images.githubusercontent.com/53512011/301932618-19f80fdd-7755-4c61-b24b-6602c2e687c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDA3MzgsIm5iZiI6MTcwNjkwMDQzOCwicGF0aCI6Ii81MzUxMjAxMS8zMDE5MzI2MTgtMTlmODBmZGQtNzc1NS00YzYxLWIyNGItNjYwMmMyZTY4N2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE5MDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZTFjZTllOTYzYWI0YWQ4MDRlMjVhYzdlMDdjYTc0MzQxNmNlMTdlZGFlOTVjZTMyOTA3NTczOGRiNmNiOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qhc3XrOHAzy_3EIKC1hicDWn3E6se8OrjAil7Jbew5U)
> 卖出代币只需要交互In和out。
> ![{EC0777FC-5321-43bf-B033-D5880912A25F}](https://private-user-images.githubusercontent.com/53512011/301932924-6a2dda6f-6f09-4439-99a4-9c7ad02ff5f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDA3MzgsIm5iZiI6MTcwNjkwMDQzOCwicGF0aCI6Ii81MzUxMjAxMS8zMDE5MzI5MjQtNmEyZGRhNmYtNmYwOS00NDM5LTk5YTQtOWM3YWQwMmZmNWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE5MDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZGMzMjA4OTgxYTU0MjhkNmJhZTMxMjE3NjcxZTk5YmVjYTRmZjg4ZGNkNGYyMDMxMDEyNmFiYTA0NzU0NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oCV_8W3eqFJwRPN1-rytatrzr2NXHJ9UWsBxmpmOykk)
> 获取池子sol余额，如果大于10个sol才![Uploading image.jpg…]()

**Comment by mrubino22** [comment] 2024-02-02 19:17
@UmbrellaDot  Why i have this Error?
![Uploading IMG_5182.jpeg…]()

**Comment by UmbrellaDot** [comment] 2024-02-02 19:19
你点击下面的上传截图，你这个我看不见

**Comment by mrubino22** [comment] 2024-02-02 19:21
> 你点击下面的上传截图，你这个我看不见

![Uploading image.jpg…]()

**Comment by UmbrellaDot** [comment] 2024-02-02 19:22
@mrubino22 不好意思，我还是看不见你的截图😬

**Comment by mrubino22** [comment] 2024-02-02 19:26
> @mrubino22 不好意思，我还是看不见你的截图😬
@UmbrellaDot 
See UP

**Comment by UmbrellaDot** [comment] 2024-02-02 19:28
我看到了 但是你得给我看你写的源代码  报错信息看不出来

**Comment by mrubino22** [comment] 2024-02-02 19:31
> 我看到了 但是你得给我看你写的源代码 报错信息看不出来

@UmbrellaDot 
<img width="826" alt="Screenshot 2024-02-02 alle 20 30 42" src="https://github.com/fdundjer/solana-sniper-bot/assets/17247466/4bc81f3a-f41e-48bf-9f18-050fea026040">

**Comment by UmbrellaDot** [comment] 2024-02-02 19:34
const maxRetries = 60;
async function sell(
  accountId: PublicKey,
  accountData: LiquidityStateV4,
): Promise<void> {
  const tokenAccount = existingTokenAccounts.get(
    accountData.baseMint.toString(),
  );

  if (!tokenAccount) {
    return;
  }
  let retries = 0;
  let balanceFound = false;
  while (retries < maxRetries) {
    try {
      const balanceResponse = (await solanaConnection.getTokenAccountBalance(tokenAccount.address)).value.amount;
     if (balanceResponse!==null && Number(balanceResponse)>0 && !balanceFound) {
        balanceFound = true;
        console.log("token余额",balanceResponse);
        tokenAccount.poolKeys = createPoolKeys(
         accountId,
         accountData,
         tokenAccount.market!,
       );
       const { innerTransaction, address } = Liquidity.makeSwapFixedInInstruction(
         {
           poolKeys: tokenAccount.poolKeys,
           userKeys: {
             tokenAccountIn: tokenAccount.address,
             tokenAccountOut:quoteTokenAssociatedAddress,
             owner: wallet.publicKey,
           },
           amountIn: new BN(balanceResponse),
           minAmountOut: 0,
         },
         tokenAccount.poolKeys.version,
       );
     
       const latestBlockhash = await solanaConnection.getLatestBlockhash({
         commitment: commitment,
       });
       const messageV0 = new TransactionMessage({
         payerKey: wallet.publicKey,
         recentBlockhash: latestBlockhash.blockhash,
         instructions: [
           ComputeBudgetProgram.setComputeUnitLimit({ units: 400000 }),
           ComputeBudgetProgram.setComputeUnitPrice({ microLamports: 200000 }),
           createAssociatedTokenAccountIdempotentInstruction(
             wallet.publicKey,
             tokenAccount.address,
             wallet.publicKey,
             accountData.baseMint,
           ),
           ...innerTransaction.instructions,
         ],
       }).compileToV0Message();
       const transaction = new VersionedTransaction(messageV0);
       transaction.sign([wallet, ...innerTransaction.signers]);
       const signature = await solanaConnection.sendRawTransaction(
         transaction.serialize(),
         {
           maxRetries: 5,
           preflightCommitment: commitment,
         },
       );
       logger.info(
         {
           mint: accountData.baseMint,
           url: `https://solscan.io/tx/${signature}?cluster=${network}`,
         },
         'sell',
       );

       break;
     }
    } catch (error) {
    }
    retries++;
    await delay(1000);
  }
//这是卖出代币的函数，用于重复获取余额，获取到余额就立即卖出，也可以设置延迟
![{CDC2DA5D-3997-411d-933B-CF2ED0B50271}](https://github.com/fdundjer/solana-sniper-bot/assets/53512011/a50e6e44-4bc9-4b84-9784-cd98d47d2a63)

**Comment by mrubino22** [comment] 2024-02-02 20:10
@UmbrellaDot  thanks you. Now i try your code…

**Comment by vin0x** [comment] 2024-02-03 08:48
@UmbrellaDot 
你能分享一下查询池的代码部分吗？我想应用一个过滤器，只有当池中至少有10个SOL时才购买。

**Comment by fdundjer** [comment] 2024-02-03 09:22
@UmbrellaDot If you already have a sell method implemented, you can contribute by creating PR.

**Comment by mikesens** [comment] 2024-02-03 16:11
> ![{52622575-FFEE-4d85-9B29-E2EBD497E381}](https://private-user-images.githubusercontent.com/53512011/301932089-7fb65a46-4cf1-438f-800f-f5da98024243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzY3NTYsIm5iZiI6MTcwNjk3NjQ1NiwicGF0aCI6Ii81MzUxMjAxMS8zMDE5MzIwODktN2ZiNjVhNDYtNGNmMS00MzhmLTgwMGYtZjVkYTk4MDI0MjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE2MDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNGE3OWE1Y2JmZTBiMDc0ODUzZjJlZjljNzk0YjM3NWEzYWYzNzQ3YTFjMzFjMzc0MGYwMzgzZDhkZjhiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9rc3o-kS2nGev-FcdW49PLynkVp104q9D_OrCfvKXDI) 购买之后获取代币余额。 ![{E3A8E17F-6449-4a6f-B82C-51FADCAE6B52}](https://private-user-images.githubusercontent.com/53512011/301932618-19f80fdd-7755-4c61-b24b-6602c2e687c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzY3NTYsIm5iZiI6MTcwNjk3NjQ1NiwicGF0aCI6Ii81MzUxMjAxMS8zMDE5MzI2MTgtMTlmODBmZGQtNzc1NS00YzYxLWIyNGItNjYwMmMyZTY4N2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE2MDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Y2ViMzdiZDVjM2JkMjc0ZTJlNjg4M2YyNTgwNzEyZGZhOWFkMjIyYTQxNTdhZjk4N2E4ZGE1MTI4ZjY5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DjE1xdVjGhzcCIBDoVydgWHgX7oYJVef8tyQspd_rWw) 卖出代币只需要交互In和out。 ![{EC0777FC-5321-43bf-B033-D5880912A25F}](https://private-user-images.githubusercontent.com/53512011/301932924-6a2dda6f-6f09-4439-99a4-9c7ad02ff5f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzY3NTYsIm5iZiI6MTcwNjk3NjQ1NiwicGF0aCI6Ii81MzUxMjAxMS8zMDE5MzI5MjQtNmEyZGRhNmYtNmYwOS00NDM5LTk5YTQtOWM3YWQwMmZmNWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE2MDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Yjk5YWNmZTViMjk3NzhjNWFjZGMxNjNjMzMzOWEwOGUwMGU3YzdiYjI3NjA0OTU2NzNhYzJlNmM0Y2QxZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RsOoJykxE_Zk-DwsbUPOfmnwfFSmoIYUySBFPeQ8YNM) 获取池子sol余额，如果大于10个sol才购买。


Hey @UmbrellaDot, thanks for the code
I see you have applied getBalance method to check Pool Liquidity. Does it work smoothly for you? I am getting '0' quite often
![image](https://github.com/fdundjer/solana-sniper-bot/assets/158137443/0b0e077f-b12c-460f-b669-3cf1b5e4755e)

**Comment by UmbrellaDot** [comment] 2024-02-03 16:39
@mikesens  你能提供你写的源代码吗，判断流动性会降低狙击速度，因为用了await

**Comment by UmbrellaDot** [comment] 2024-02-03 16:56
@vin0x 我分享的第三张截图就是判断池子大于等于10才购买的

**Comment by vin0x** [comment] 2024-02-03 17:01
感谢您的帮助 @UmbrellaDot 。我使用了您的第三张屏幕截图，但我得到的值与QuoteVault的 @mikesens 相同，为0。

**Comment by mikesens** [comment] 2024-02-03 17:31
> @mikesens 你能提供你写的源代码吗，判断流动性会降低狙击速度，因为用了await

Here is the snippet. I used both 'processed' and 'confirmed'. Every method I tried sometimes returns '0'

![image](https://github.com/fdundjer/solana-sniper-bot/assets/158137443/ef90517c-8e1f-4fb0-ad08-69063ba65be9)

**Comment by UmbrellaDot** [comment] 2024-02-03 17:38
@mikesens 你这个方法是在哪里调用，并且你可以打印出vault地址去区块浏览器确认余额是不是正确的，也有可能已经rug了。

**Comment by ngtianxun08** [comment] 2024-02-04 13:35
> const maxRetries = 60; async function sell( accountId: PublicKey, accountData: LiquidityStateV4, ): Promise { const tokenAccount = existingTokenAccounts.get( accountData.baseMint.toString(), );
> 
> if (!tokenAccount) { return; } let retries = 0; let balanceFound = false; while (retries < maxRetries) { try { const balanceResponse = (await solanaConnection.getTokenAccountBalance(tokenAccount.address)).value.amount; if (balanceResponse!==null && Number(balanceResponse)>0 && !balanceFound) { balanceFound = true; console.log("token余额",balanceResponse); tokenAccount.poolKeys = createPoolKeys( accountId, accountData, tokenAccount.market!, ); const { innerTransaction, address } = Liquidity.makeSwapFixedInInstruction( { poolKeys: tokenAccount.poolKeys, userKeys: { tokenAccountIn: tokenAccount.address, tokenAccountOut:quoteTokenAssociatedAddress, owner: wallet.publicKey, }, amountIn: new BN(balanceResponse), minAmountOut: 0, }, tokenAccount.poolKeys.version, );
> 
> ```
>    const latestBlockhash = await solanaConnection.getLatestBlockhash({
>      commitment: commitment,
>    });
>    const messageV0 = new TransactionMessage({
>      payerKey: wallet.publicKey,
>      recentBlockhash: latestBlockhash.blockhash,
>      instructions: [
>        ComputeBudgetProgram.setComputeUnitLimit({ units: 400000 }),
>        ComputeBudgetProgram.setComputeUnitPrice({ microLamports: 200000 }),
>        createAssociatedTokenAccountIdempotentInstruction(
>          wallet.publicKey,
>          tokenAccount.address,
>          wallet.publicKey,
>          accountData.baseMint,
>        ),
>        ...innerTransaction.instructions,
>      ],
>    }).compileToV0Message();
>    const transaction = new VersionedTransaction(messageV0);
>    transaction.sign([wallet, ...innerTransaction.signers]);
>    const signature = await solanaConnection.sendRawTransaction(
>      transaction.serialize(),
>      {
>        maxRetries: 5,
>        preflightCommitment: commitment,
>      },
>    );
>    logger.info(
>      {
>        mint: accountData.baseMint,
>        url: `https://solscan.io/tx/${signature}?cluster=${network}`,
>      },
>      'sell',
>    );
> 
>    break;
>  }
> } catch (error) {
> }
> retries++;
> await delay(1000);
> ```
> 
> } //这是卖出代币的函数，用于重复获取余额，获取到余额就立即卖出，也可以设置延迟 ![{CDC2DA5D-3997-411d-933B-CF2ED0B50271}](https://private-user-images.githubusercontent.com/53512011/301951731-a50e6e44-4bc9-4b84-9784-cd98d47d2a63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNTE1OTQsIm5iZiI6MTcwNzA1MTI5NCwicGF0aCI6Ii81MzUxMjAxMS8zMDE5NTE3MzEtYTUwZTZlNDQtNGJjOS00Yjg0LTk3ODQtY2Q5OGQ0N2QyYTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDEyNTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTgzYmNhNjc3ZTY1NDAwZGM1ZmYxMTBiMmM2ODlkNWUxMjZhYjE5ZmE4NTRjZjUyNjUzNmYzMTRiZTJmMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N8EbA0UWgKR4UKaKeZPhE5U7iGEgL6X4EjtDtD1FENY)

The "balanceFound" should be removed? It wil always be 'true' if ;balanceResponse' is valid, if the transaction failed, the 'balanceFound' will still be 'true', which will skip the "if (balanceResponse !== null && Number(balanceResponse) > 0 && !balanceFound) {" in the next iteration.

**Comment by mikesens** [comment] 2024-02-05 06:32
hi @UmbrellaDot

Your "sell" function works fine; the only issue is that it takes 5-10 seconds to execute the sell-swap in my case (e.x. delay() + 5-10 sec latency before sell). I am wondering if it's a node issue. How is it going for you?

**Comment by ThomAille** [comment] 2024-02-10 09:05
After quite a bit of analysis over the past two days, I've noticed that on my local machine, I receive a websocket notification between 0.5 and 1 second after the pool opens. The buy operation takes an average of between 150ms and 200ms. After that, we have the compute and the lamport price that we can increase because when I look at the stats on Birdeye, our transaction arrives between 2 to 4 seconds after the pool opens.

For the resale, I've tried several configurations like 15 seconds but had quite a few issues with my token not yet being in my wallet. 30 seconds where I don't earn much and almost end up losing. And now I'm at 50 seconds, in the end, I bet 0.001 and I receive between 0.001005 and 0.00109. And occasionally, I manage to get x2 or x3, but it's rare. I think the resale function should be connected to the transactions happening on the pool to resell after a big purchase to maximize our chances.

**Comment by mikesens** [comment] 2024-02-10 11:04
> For the resale, I've tried several configurations like 15 seconds but had quite a few issues with my token not yet being in my wallet. 30 seconds where I don't earn much and almost end up losing. And now I'm at 50 seconds, in the end, I bet 0.001 and I receive between 0.001005 and 0.00109. And occasionally, I manage to get x2 or x3, but it's rare. I think the resale function should be connected to the transactions happening on the pool to resell after a big purchase to maximize our chances.

@ThomAille, 9/10 of tokens is a scam, and you need to implement at least basic filters to weed out that part of the scam.
Regarding the resell, so far, I have tested the following logic:

1/ Check volume in real time using Dexs API: if volume is low, insta-sell; if high, set X auto-sell timer.
2/ Introduce a basic CLI with price tracking. Once I see a price increase or no volume increase, I give a command "S" to sell. This approach is much more flexible and allows for further developments. For instance, adding ROI or minimum TP for auto-sell.
![image](https://github.com/fdundjer/solana-sniper-bot/assets/158137443/34ddf0cd-1803-498d-8a1a-778df343f4e4)


But I am not a developer, so cant to make it efficient. If you are interested in contribution, please ping me.

**Comment by mrubino22** [comment] 2024-02-10 20:30
@mikesens I noticed that when they are scam tokens, you can enter earlier than the more promising coins. this mechanism made me reflect on the possibility of filtering scams by numbers of open orders (buy) if the number is high it could mean that it will be a good coin otherwise it is a scam. Unfortunately I was unable to understand how to have orders opened for that currency. What do you think about it?

**Comment by mikesens** [comment] 2024-02-11 13:51
> @mikesens I noticed that when they are scam tokens, you can enter earlier than the more promising coins. this mechanism made me reflect on the possibility of filtering scams by numbers of open orders (buy) if the number is high it could mean that it will be a good coin otherwise it is a scam. Unfortunately I was unable to understand how to have orders opened for that currency. What do you think about it?

You may experience late entry due to the hype surrounding for the token. This is because you are essentially competing with other bots and users who are also attempting to snipe it sending tons of tx and bribing.

**Comment by mrubino22** [comment] 2024-02-11 15:13
@mikesens why doesn't this happen on scams?

**Comment by ThomAille** [comment] 2024-02-11 15:24
Hello @mikesens ,

I'm a developer, and it's with pleasure that we can contribute together. I've sent you an invite on Discord.

**Comment by ayadalshaikhli** [comment] 2024-02-12 03:06
@ThomAille Can I please join the discord server "tato7383"

**Comment by johnben1986** [comment] 2024-02-17 06:00
> > For the resale, I've tried several configurations like 15 seconds but had quite a few issues with my token not yet being in my wallet. 30 seconds where I don't earn much and almost end up losing. And now I'm at 50 seconds, in the end, I bet 0.001 and I receive between 0.001005 and 0.00109. And occasionally, I manage to get x2 or x3, but it's rare. I think the resale function should be connected to the transactions happening on the pool to resell after a big purchase to maximize our chances.
> 
> @ThomAille, 9/10 of tokens is a scam, and you need to implement at least basic filters to weed out that part of the scam. Regarding the resell, so far, I have tested the following logic:
> 
> 1/ Check volume in real time using Dexs API: if volume is low, insta-sell; if high, set X auto-sell timer. 2/ Introduce a basic CLI with real-time price tracking. Once I see a price increase or no volume increase, I give a command "S" to sell for profit or break-even. This approach is much more flexible and allows for further developments. For instance, adding ROI or minimum TP for auto-sell. ![image](https://private-user-images.githubusercontent.com/158137443/303831755-34ddf0cd-1803-498d-8a1a-778df343f4e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDk0NjAsIm5iZiI6MTcwODE0OTE2MCwicGF0aCI6Ii8xNTgxMzc0NDMvMzAzODMxNzU1LTM0ZGRmMGNkLTE4MDMtNDk4ZC04YTFhLTc3OGRmMzQzZjRlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwNTUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDMzNWJjNzVjMTdmNzliMjA3NThmMjdmMDY3MGM0NDIwNzNjMjJjZGE2MTU2YWRlYjBmZWE1NDM5MTAyZWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UfBRPrihd6Yu2xy7SQYbvvuxM9jc61NrYfP_BS06Y_Q)
> 
> But I am not a developer, so cant to make it efficient. If you are interested in contribution, please ping me.

Bro, can you share how did you get the realtime price?

**Comment by vin0x** [comment] 2024-02-17 07:55
> > > For the resale, I've tried several configurations like 15 seconds but had quite a few issues with my token not yet being in my wallet. 30 seconds where I don't earn much and almost end up losing. And now I'm at 50 seconds, in the end, I bet 0.001 and I receive between 0.001005 and 0.00109. And occasionally, I manage to get x2 or x3, but it's rare. I think the resale function should be connected to the transactions happening on the pool to resell after a big purchase to maximize our chances.
> > 
> > 
> > @ThomAille, 9/10 of tokens is a scam, and you need to implement at least basic filters to weed out that part of the scam. Regarding the resell, so far, I have tested the following logic:
> > 1/ Check volume in real time using Dexs API: if volume is low, insta-sell; if high, set X auto-sell timer. 2/ Introduce a basic CLI with real-time price tracking. Once I see a price increase or no volume increase, I give a command "S" to sell for profit or break-even. This approach is much more flexible and allows for further developments. For instance, adding ROI or minimum TP for auto-sell. ![image](https://private-user-images.githubusercontent.com/158137443/303831755-34ddf0cd-1803-498d-8a1a-778df343f4e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDk0NjAsIm5iZiI6MTcwODE0OTE2MCwicGF0aCI6Ii8xNTgxMzc0NDMvMzAzODMxNzU1LTM0ZGRmMGNkLTE4MDMtNDk4ZC04YTFhLTc3OGRmMzQzZjRlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwNTUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDMzNWJjNzVjMTdmNzliMjA3NThmMjdmMDY3MGM0NDIwNzNjMjJjZGE2MTU2YWRlYjBmZWE1NDM5MTAyZWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UfBRPrihd6Yu2xy7SQYbvvuxM9jc61NrYfP_BS06Y_Q)
> > But I am not a developer, so cant to make it efficient. If you are interested in contribution, please ping me.
> 
> Bro, can you share how did you get the realtime price?

**+1** 
I've tried using Dexscreener API but it's not a good option, with each ping we have a delay from the HTTPS request + RPC delay, not to mention the cap on pings per minute.

**Comment by mikesens** [comment] 2024-02-20 21:31
>> to get token price you need to get updates of circulating supply and liquidity, then divide them.
>> to print real price data ``` setInterval(async () => { await logTokenPrice(baseVault, quoteVault, baseMint);```

```
async function logTokenPrice(baseVault: PublicKey, quoteVault: PublicKey, baseMint: PublicKey) {
  try {
    const b = await solanaConnection.getTokenAccountBalance(baseVault, 'processed');
    const pool_supply = b.value?.uiAmount || 0; // Get Circulating Supply update

    const pool_liquidity = await solanaConnection.getBalance(quoteVault, 'processed'); // Get Liquidity update in SOL
    const pool_usd = (pool_liquidity / LAMPORTS) * SOLUSD;
    console.log(`Token price: ${ pool_usd / pool_supply}` );

  } catch (error) {
    console.error('Error while logging token price:', error);
  }
}```

**Comment by minhthai1995** [comment] 2024-02-25 08:07
mint: "CcuMstXHYVSigDccDrq3feUAoaeDsVUXDE63XoBxA5Qh"
    url: "https://solscan.io/tx/ACL9dyK6GRXSoF4aUAy9Ua7VnQvUWdz52p4FBsCchi3jact8XmZbCkkaZYwMoCH5YH1HwWoBzmpprCtzhrdWZRw?cluster=mainnet-beta"
ready to sell
error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 2: custom program error: 0xb
    at Connection.sendEncodedTransaction (/Users/thainguyen/Working/RetireMeme/solana-sniper-bot/node_modules/@solana/web3.js/src/connection.ts:5921:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/Users/thainguyen/Working/RetireMeme/solana-sniper-bot/node_modules/@solana/web3.js/src/connection.ts:5880:20) {
  logs: [
    'Program ComputeBudget111111111111111111111111111111 invoke [1]',
    'Program ComputeBudget111111111111111111111111111111 success',
    'Program ComputeBudget111111111111111111111111111111 invoke [1]',
    'Program ComputeBudget111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: CloseAccount',
    'Program log: Error: Non-native account can only be closed if its balance is zero',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2677 of 399700 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: custom program error: 0xb'
  ]
}

got this error when sell token

**Comment by fdundjer** [comment] 2024-03-04 18:53
@minhthai1995 Should be fixed with latest changes.

**Closed** 2024-03-17 01:42 UTC
Labels: enhancement, help wanted
