### ISSUE TITLE
Empty Transaction

### ISSUE THREAD

**Issue by mrubino22** [fdundjer/solana-sniper-bot#23] opened 2024-02-01 15:16 UTC
@fdundjer why many times does he say he has purchased but in reality he doesn't?
![IMG_5181](https://github.com/fdundjer/solana-sniper-bot/assets/17247466/03e2f49c-f19a-48f9-bcc3-789ad05aaad6)

**Comment by mikesens** [comment] 2024-02-01 15:25
i had similar issue, as suggestion - try to play w/:
- commitment: finalized, confirmed, processed
- wallet and sufficient WSOL (not all wallets worked in my case), Phantom works fine

**Comment by mrubino22** [comment] 2024-02-01 15:45
> i had similar issue, as suggestion - try to play w/:
> 
> * commitment: finalized, confirmed, processed
> * wallet and sufficient WSOL (not all wallets worked in my case), Phantom works fine

I set processed, and I fund Sol in the Phantom Wallet (he manages to buy me some yes and a lot others no)... even if my biggest problem is selling because I don't have the sell method

**Comment by mrubino22** [comment] 2024-02-01 16:26
> > > i had similar issue, as suggestion - try to play w/:
> > > 
> > > * commitment: finalized, confirmed, processed
> > > * wallet and sufficient WSOL (not all wallets worked in my case), Phantom works fine
> > 
> > 
> > I set processed, and I fund wSol in the Phantom Wallet (he manages to buy me some yes and a lot others no)... even if my biggest problem is selling because I don't have the sell method
> 
> * Set to 'confirmed' then tx will be passed. Works for me.
> * Regarding sell. Temporary solution: find a bot w/ wallet import function + nice GUI for quick sell (all sniped coin will be there).

do you have any links or bots

**Comment by fdundjer** [comment] 2024-02-01 17:22
@mrubino22 as @mikesens mentioned, this is most likely due to the commitment level.
Change the commitment level to confirmed/finalized and you'll have more successful transactions.
I'll update the readme that explains why this happens.

**Comment by fdundjer** [comment] 2024-02-03 09:20
@mrubino22 I've updated the readme. I'll close the issue.

**Closed by fdundjer** 2024-02-03 09:20 UTC
Labels: question
